spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        druid:
              initial-size: 5
              min-idle: 5
              max-active: 20
              # 连接等待超时时间
              max-wait: 30000
              # 配置检测可以关闭的空闲连接间隔时间
              time-between-eviction-runs-millis: 60000
              # 配置连接在池中的最小生存时间
              min-evictable-idle-time-millis: 300000
              validation-query: select '1' from dual
              test-while-idle: true
              test-on-borrow: false
              test-on-return: false
              # 打开PSCache，并且指定每个连接上PSCache的大小
              pool-prepared-statements: true
              max-open-prepared-statements: 20
              max-pool-prepared-statement-per-connection-size: 20
              # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
              filters: stat,wall
              # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
              aop-patterns: com.springboot.servie.*


              # WebStatFilter配置
              web-stat-filter:
                enabled: true
                # 添加过滤规则
                url-pattern: /*
                # 忽略过滤的格式
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

              # StatViewServlet配置
              stat-view-servlet:
                enabled: true
                # 访问路径为/druid时，跳转到StatViewServlet
                url-pattern: /druid/*
                # 是否能够重置数据
                reset-enable: false
                # 需要账号密码才能访问控制台
                login-username: druid
                login-password: druid123
                # IP白名单
                allow: 127.0.0.1
                #　IP黑名单（共同存在时，deny优先于allow）
                deny: 192.168.1.218

              # 配置StatFilter
              filter:
                stat:
                  log-slow-sql: true
#    devtools:
#      restart:
#        enabled: true
    jackson:
        #日期格式化
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
           #格式化输出
          indent_output: true
          #忽略无法转换的对象
          fail_on_empty_beans: false
        #设置空如何序列化
        defaultPropertyInclusion: NON_EMPTY
        deserialization:
          #允许对象忽略json中不存在的属性
          fail_on_unknown_properties: false
        parser:
          #允许出现特殊字符和转义符
          allow_unquoted_control_chars: true
          #允许出现单引号
          allow_single_quotes: true
    mail:
        host: smtp.163.com
        username: xxxx@163.com
        password: xxxx
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
    thymeleaf:
        cache: false

    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
mybatis:
  type-aliases-package: com.example.springalltest.business.bean
  mapper-locations: classpath:mapping/*

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: ERROR
      mybatis: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  file: mylogfile.log
  pattern:
      file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
      console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'